# Generated by Django 5.0.14 on 2026-03-04 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_management', '0004_jobapplication_ai_rank_jobapplication_ai_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('SCREENING', 'Screening'), ('TECHNICAL', 'Technical'), ('HR', 'HR'), ('FINAL', 'Final')], default='SCREENING', max_length=32)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=32)),
                ('candidate_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('RESCHEDULE_REQUESTED', 'Reschedule requested'), ('DECLINED', 'Declined')], default='PENDING', max_length=32)),
                ('final_decision', models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On hold')], default='PENDING', max_length=32)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('mode', models.CharField(default='Online', max_length=32)),
                ('location_or_link', models.CharField(blank=True, max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='job_management.jobapplication')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_as_interviewer', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='job_management.job')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
    ]
