# Generated by Django 5.0.14 on 2026-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0003_job_application_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='predicted_label',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
