# Generated by Django 5.0.14 on 2026-03-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0004_jobapplication_ai_rank_jobapplication_ai_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='matched_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
