# Generated by Django 5.2.12 on 2026-03-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0005_jobapplication_matched_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='core_skills',
            field=models.TextField(blank=True, help_text='Comma or line separated core skills (e.g. Python, SQL, Docker)'),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum total years of experience expected for this role', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_education',
            field=models.CharField(blank=True, help_text='Target education level (e.g. BTech CSE, MSc Data Science)', max_length=255),
        ),
    ]
