# Generated by Django 5.0.14 on 2026-03-02 11:55

import apps.resume_management.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resume_management_resume',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.resume_management.models.resume_version_upload_path)),
                ('raw_text', models.TextField(blank=True, help_text='Extracted text for NLP/AIML')),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured fields if any')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resume_management.resume')),
            ],
            options={
                'db_table': 'resume_management_resumeversion',
                'ordering': ['-version_number'],
                'unique_together': {('resume', 'version_number')},
            },
        ),
    ]
